version: '2'
services:
    jobserver-app:
        image: jobserver
        external_links:
            - jobserver-mysql:mysql
            - jobserver-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jobserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jobserver-mysql:
        extends:
            file: mysql.yml
            service: jobserver-mysql
    jobserver-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jobserver-elasticsearch
