version: '2'
services:
    jobserver-elasticsearch:
        container_name: jobserver-elasticsearch
        image: elasticsearch:2.3.5
        # volumes:
        #     - ~/volumes/jhipster/jobserver/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
